@startuml

class Player {
  strategy
  nextHand()
  win()
  lose()
  even()
}

interface Strategy {
  nextHand()
  study()
}

class WinningStrategy {
  nextHand()
  study()
}

class ProbStrategy {
  nextHand()
  study()
}

Player o-r->Strategy
Strategy <|.d. WinningStrategy
Strategy <|.d. ProbStrategy

@enduml